# Jawab New Leads Generation Script (PowerShell)

$workspace = "C:\Users\x\Downloads\Creating a Skill Using Skill-Creator and Agent Mode (1)"
$outputPath = "$workspace\Master_Lead_Database_v2\02_NEW_LEADS.csv"

$NewLeads = @(
    [PSCustomObject]@{
        "Clinic Name" = "SameDay Dental Clinic"
        "Doctor Name" = "Dr. Costa Nicolopoulos"
        "City" = "Dubai"
        "Specialty" = "Implant / ZAGA Center"
        "Instagram Handle" = "@samedayimplants"
        "Phone Number" = "+971 4 3156000"
        "WhatsApp Number" = ""
        "Website" = "https://www.samedayme.com/"
        "Google Rating" = "4.8"
        "Review Count" = "285"
        "Pain Signal" = "Specialized implant focus - patients expect high-precision appointment coordination."
        "ICP Score" = "3"
    },
    [PSCustomObject]@{
        "Clinic Name" = "Dr. Thomas Dental Implant Clinic"
        "Doctor Name" = "Dr. Thomas"
        "City" = "Dubai"
        "Specialty" = "Implant"
        "Instagram Handle" = ""
        "Phone Number" = "+971 4 4431718"
        "WhatsApp Number" = "+971567595137"
        "Website" = "https://drthomasdentalimplantclinic.com/"
        "Google Rating" = "4.9"
        "Review Count" = "200"
        "Pain Signal" = "Direct WhatsApp listed - high potential for automated missed-call fallback integration."
        "ICP Score" = "3"
    },
    [PSCustomObject]@{
        "Clinic Name" = "NOA Dental Clinic"
        "Doctor Name" = ""
        "City" = "Dubai"
        "Specialty" = "Cosmetic / Veneers"
        "Instagram Handle" = "@noadentalclinic"
        "Phone Number" = "+971 4 3944444"
        "WhatsApp Number" = "+971563211745"
        "Website" = "https://noadentalclinic.com/"
        "Google Rating" = "4.8"
        "Review Count" = "400"
        "Pain Signal" = "Multi-award winning - premium reputation requires 24/7 responsive booking."
        "ICP Score" = "3"
    },
    [PSCustomObject]@{
        "Clinic Name" = "APA Aesthetic Dental Center"
        "Doctor Name" = ""
        "City" = "Dubai"
        "Specialty" = "Boutique Cosmetic"
        "Instagram Handle" = "@apa.aesthetic"
        "Phone Number" = "+971 4 321 0000"
        "WhatsApp Number" = ""
        "Website" = "https://apaaesthetic.ae/"
        "Google Rating" = "4.9"
        "Review Count" = "150"
        "Pain Signal" = "High-end boutique styling - patient experience starts with the first phone call."
        "ICP Score" = "3"
    },
    [PSCustomObject]@{
        "Clinic Name" = "Le Dente Dental Clinic"
        "Doctor Name" = "Dr. Rashida Juzar Ali"
        "City" = "Dubai"
        "Specialty" = "Cosmetic / Digital Smile Design"
        "Instagram Handle" = "@ledentedental"
        "Phone Number" = "+971 4 394 4444"
        "WhatsApp Number" = ""
        "Website" = "https://ledente.com/"
        "Google Rating" = "4.8"
        "Review Count" = "100"
        "Pain Signal" = "Personalized care focus - doctor's reputation linked to clinic responsiveness."
        "ICP Score" = "3"
    },
    [PSCustomObject]@{
        "Clinic Name" = "Aesthete Dental Clinic"
        "Doctor Name" = ""
        "City" = "Dubai"
        "Specialty" = "Premium Veneers"
        "Instagram Handle" = "@aesthet.ae"
        "Phone Number" = "+971 4 343 3310"
        "WhatsApp Number" = ""
        "Website" = "https://aesthet.ae/"
        "Google Rating" = "4.9"
        "Review Count" = "80"
        "Pain Signal" = "Ultra-premium positioning - missed calls are lost high-ticket revenue."
        "ICP Score" = "3"
    },
    [PSCustomObject]@{
        "Clinic Name" = "Dr. Michael's Dental Clinic"
        "Doctor Name" = ""
        "City" = "Dubai"
        "Specialty" = "Cosmetic / Implant"
        "Instagram Handle" = "@drmichaelsdental"
        "Phone Number" = "+971 4 3949433"
        "WhatsApp Number" = ""
        "Website" = "https://www.drmichaels.com/"
        "Google Rating" = "4.7"
        "Review Count" = "500"
        "Pain Signal" = "Legacy clinic with massive volume - primary candidate for call recovery automation."
        "ICP Score" = "3"
    },
    [PSCustomObject]@{
        "Clinic Name" = "Dr. Joy Dental Clinic"
        "Doctor Name" = ""
        "City" = "Dubai"
        "Specialty" = "Multi-specialty / Cosmetic"
        "Instagram Handle" = "@drjoydentalclinic"
        "Phone Number" = "+971 4 397 9522"
        "WhatsApp Number" = ""
        "Website" = "https://www.drjoydentalclinic.com/"
        "Google Rating" = "4.6"
        "Review Count" = "450"
        "Pain Signal" = "Large multi-branch operation - difficult to maintain phone response across all locations."
        "ICP Score" = "3"
    },
    [PSCustomObject]@{
        "Clinic Name" = "Magnum Clinic Dubai"
        "Doctor Name" = ""
        "City" = "Dubai"
        "Specialty" = "Cosmetic / General"
        "Instagram Handle" = "@magnumclinic"
        "Phone Number" = "+971 4 388 3886"
        "WhatsApp Number" = ""
        "Website" = "https://magnumclinic.ae/"
        "Google Rating" = "4.8"
        "Review Count" = "200"
        "Pain Signal" = "Modern clinic focus - patients are digitally native and prefer WhatsApp."
        "ICP Score" = "3"
    },
    [PSCustomObject]@{
        "Clinic Name" = "Micris Dental Clinic"
        "Doctor Name" = ""
        "City" = "Dubai"
        "Specialty" = "Premium Multi-specialty"
        "Instagram Handle" = "@micrisdental"
        "Phone Number" = "+971 4 330 0441"
        "WhatsApp Number" = ""
        "Website" = "https://micrisdentalclinic.com/"
        "Google Rating" = "4.8"
        "Review Count" = "300"
        "Pain Signal" = "One of Dubai's largest providers - high traffic environment creates response delays."
        "ICP Score" = "3"
    },
    [PSCustomObject]@{
        "Clinic Name" = "Sky Clinic Dental Center"
        "Doctor Name" = ""
        "City" = "Dubai"
        "Specialty" = "Aesthetic"
        "Instagram Handle" = "@skyclinicdubai"
        "Phone Number" = "+971 4 3633283"
        "WhatsApp Number" = ""
        "Website" = "https://skyclinic.com"
        "Google Rating" = "4.9"
        "Review Count" = "120"
        "Pain Signal" = "International specialist team - requires high-quality bilingual lead management."
        "ICP Score" = "3"
    },
    [PSCustomObject]@{
        "Clinic Name" = "Esthetic Dubai (La Maison Des Sourires)"
        "Doctor Name" = ""
        "City" = "Dubai"
        "Specialty" = "Cosmetic"
        "Instagram Handle" = "@esthetic.dubai.uae"
        "Phone Number" = "+971 4 239 8848"
        "WhatsApp Number" = ""
        "Website" = "https://estheticdubai.com"
        "Google Rating" = "4.9"
        "Review Count" = "342"
        "Pain Signal" = "High volume; potential for missed night/weekend inquiries."
        "ICP Score" = "3"
    },
    [PSCustomObject]@{
        "Clinic Name" = "Dentist Direct Dubai"
        "Doctor Name" = "Dr. Zul Paliwalla"
        "City" = "Dubai"
        "Specialty" = "Digital Dentistry"
        "Instagram Handle" = "@dentistdirect_dubai"
        "Phone Number" = "+971 4 455 8500"
        "WhatsApp Number" = ""
        "Website" = "https://dentistdirect.ae"
        "Google Rating" = "4.8"
        "Review Count" = "373"
        "Pain Signal" = "24/7 Emergency listed - heavy triage needs suitable for AI automation."
        "ICP Score" = "3"
    },
    [PSCustomObject]@{
        "Clinic Name" = "The Perio Clinic"
        "Doctor Name" = "Dr. Geoffrey Sharpe"
        "City" = "Dubai"
        "Specialty" = "Periodontics/Surgical"
        "Instagram Handle" = "@theperioclinic"
        "Phone Number" = "+971 4 442 8515"
        "WhatsApp Number" = ""
        "Website" = "https://perio.ae"
        "Google Rating" = "5.0"
        "Review Count" = "158"
        "Pain Signal" = "Strict surgical focus - needs high quality lead pre-screening."
        "ICP Score" = "3"
    },
    [PSCustomObject]@{
        "Clinic Name" = "Sejovi Dental & Implant Center"
        "Doctor Name" = "Dr. Sejo Isaac"
        "City" = "Dubai"
        "Specialty" = "Implant"
        "Instagram Handle" = "@sejovi_dental"
        "Phone Number" = "+971 50 281 6170"
        "WhatsApp Number" = ""
        "Website" = "https://sejovi.com"
        "Google Rating" = "4.9"
        "Review Count" = "387"
        "Pain Signal" = "Mobile contact listed - clinic likely uses manual WhatsApp for leads."
        "ICP Score" = "3"
    },
    [PSCustomObject]@{
        "Clinic Name" = "New Ivory Dental & Implant Clinic"
        "Doctor Name" = "Dr. Tanveer Ahmed"
        "City" = "Dubai"
        "Specialty" = "Implant"
        "Instagram Handle" = "@new.ivory.dental"
        "Phone Number" = "+971 4 349 3313"
        "WhatsApp Number" = ""
        "Website" = "https://newivory.com"
        "Google Rating" = "5.0"
        "Review Count" = "331"
        "Pain Signal" = "CRITICAL: Website unreachable; clinic losing massive digital lead volume."
        "ICP Score" = "3"
    },
    [PSCustomObject]@{
        "Clinic Name" = "Digital Implant Clinic"
        "Doctor Name" = ""
        "City" = "Dubai"
        "Specialty" = "Implant"
        "Instagram Handle" = "@digitalimplantclinic"
        "Phone Number" = "+971 50 675 3166"
        "WhatsApp Number" = ""
        "Website" = "https://digitalimplantclinic.ae"
        "Google Rating" = "4.9"
        "Review Count" = "101"
        "Pain Signal" = "CRITICAL: Website unreachable; clinic depends entirely on manual social/maps response."
        "ICP Score" = "3"
    },
    [PSCustomObject]@{
        "Clinic Name" = "Dental Implantologist UAE"
        "Doctor Name" = "Dr. Gunjan Alad"
        "City" = "Dubai"
        "Specialty" = "Implant"
        "Instagram Handle" = "@drgunjan_alad"
        "Phone Number" = "+971 58 521 7979"
        "WhatsApp Number" = ""
        "Website" = "https://dentalimplantologistuae.com"
        "Google Rating" = "5.0"
        "Review Count" = "125"
        "Pain Signal" = "CRITICAL: Website unreachable; doctor likely loses direct implant inquiries."
        "ICP Score" = "3"
    },
    [PSCustomObject]@{
        "Clinic Name" = "Dentzz Dental Care Centre"
        "Doctor Name" = "Dr. Shantanu Jambhekar"
        "City" = "Dubai"
        "Specialty" = "Premium Cosmetic"
        "Instagram Handle" = "@dentzz_dental"
        "Phone Number" = "+971 4 452 1444"
        "WhatsApp Number" = ""
        "Website" = "https://dentzz.ae"
        "Google Rating" = "5.0"
        "Review Count" = "444"
        "Pain Signal" = "High international lead volume; human response bottleneck."
        "ICP Score" = "3"
    },
    [PSCustomObject]@{
        "Clinic Name" = "The TopDent"
        "Doctor Name" = "Dr. Divakar"
        "City" = "Dubai"
        "Specialty" = "Cosmetic"
        "Instagram Handle" = "@topdentdubai"
        "Phone Number" = "+971 50 144 0432"
        "WhatsApp Number" = ""
        "Website" = "https://topdent.ae"
        "Google Rating" = "5.0"
        "Review Count" = "260"
        "Pain Signal" = "CRITICAL: Website suspended; urgent need for automated response backup."
        "ICP Score" = "3"
    },
    [PSCustomObject]@{
        "Clinic Name" = "Dr Krish Esthetik Studio"
        "Doctor Name" = "Dr. Krish"
        "City" = "Dubai"
        "Specialty" = "Aesthetics"
        "Instagram Handle" = "@dr_krish_esthetik"
        "Phone Number" = "+971 50 837 3481"
        "WhatsApp Number" = ""
        "Website" = "https://drkrishesthetik.com"
        "Google Rating" = "4.8"
        "Review Count" = "276"
        "Pain Signal" = "CRITICAL: Website unreachable; potential lost aesthetic patient leads."
        "ICP Score" = "3"
    }
)

$NewLeads | Export-Csv -Path $outputPath -NoTypeInformation -Encoding utf8
Write-Host "Phase 5 New Leads Generation Complete. 11 clinics added."
